version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: products-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: products-api
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      R2DBC_URL: ${R2DBC_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      FLYWAY_JDBC_URL: ${FLYWAY_JDBC_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_SECONDS: ${JWT_EXPIRATION_SECONDS}
      JWT_ISSUER: ${JWT_ISSUER}
      AWS_REGION: ${AWS_REGION}
      AWS_DEFAULT_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_PUBLIC_BASE_URL: ${AWS_S3_PUBLIC_BASE_URL}
      AWS_S3_PREFIX: ${AWS_S3_PREFIX}
      AWS_S3_MAX_FILE_SIZE: ${AWS_S3_MAX_FILE_SIZE}
      AWS_S3_ALLOWED_CONTENT_TYPES: ${AWS_S3_ALLOWED_CONTENT_TYPES}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  auth_postgres_data:
