spring.application.name=products

app.aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:}
app.aws.s3.region=${AWS_REGION:us-east-1}
app.aws.s3.public-base-url=${AWS_S3_PUBLIC_BASE_URL:}
app.aws.s3.prefix=${AWS_S3_PREFIX:products}
app.aws.s3.max-file-size=${AWS_S3_MAX_FILE_SIZE:5242880}
app.aws.s3.allowed-content-types=${AWS_S3_ALLOWED_CONTENT_TYPES:image/jpeg,image/png,image/webp}

