apiVersion: v1
kind: Secret
metadata:
  name: products-secrets
type: Opaque
stringData:
  DB_USERNAME: "REPLACE_ME"
  DB_PASSWORD: "REPLACE_ME"
  JWT_SECRET: "replace-with-a-long-random-secret-minimum-32-characters"

